DROP TABLE Branch;
GO

CREATE TABLE Branch(
Branch_ID INT NOT NULL,
Branch_Name VARCHAR(20) NOT NULL,
Branch_Address VARCHAR(50) NOT NULL,
Branch_City VARCHAR(50) NOT NULL,
Branch_State VARCHAR(2) NOT NULL,
Branch_Zip INT NOT NULL,
PRIMARY KEY (Branch_ID)
);

DROP TABLE Customer;
GO

CREATE TABLE Customer(
Customer_ID INT NOT NULL,
FName NVARCHAR(20) NOT NULL,
LName NVARCHAR(20) NOT NULL,
Cust_Address NVARCHAR(50) NOT NULL,
Cust_City NVARCHAR(50) NOT NULL,
Cust_State NVARCHAR(2) NOT NULL,
Cust_Zip INT NOT NULL
PRIMARY KEY (Customer_ID)
);

DROP TABLE CarType;
GO

CREATE TABLE CarType(
CarTypeID INT NOT NULL,
CarType VARCHAR(10),
PRIMARY KEY (CarTypeID)
);

INSERT INTO CarType
SELECT 1,'Pickup' UNION ALL
SELECT 2, 'SUV' UNION ALL
SELECT 3, 'Compact' UNION ALL
SELECT 4, 'Mid Size'

DROP TABLE Car;
GO

CREATE TABLE Car(
Car_ID INT NOT NULL,
Price_Per_Day MONEY NOT NULL,
Initial_Milage INT NOT NULL,
CarTypeID INT NOT NULL,
Branch_ID INT NOT NULL,
PRIMARY KEY (Car_ID),
FOREIGN KEY (Branch_ID) REFERENCES Branch(Branch_ID),
FOREIGN KEY (CarTypeID) REFERENCES CarType(CarTypeID)
);

DROP TABLE Pickup
GO

CREATE TABLE Pickup(
Car_ID INT NOT NULL,
CarTypeID AS 1 PERSISTED, -- For Pickup Trucks
Make VARCHAR(15) NOT NULL,
Model VARCHAR(20) NOT NULL,
Plate_Num VARCHAR(6) NOT NULL,
PRIMARY KEY (Car_ID),
FOREIGN KEY (Car_ID) REFERENCES Car(Car_ID)
);

DROP TABLE SUV;
GO

CREATE TABLE SUV(
Car_ID INT NOT NULL,
CarTypeID AS 2 PERSISTED, -- For SUVs
Make VARCHAR(15) NOT NULL,
Model VARCHAR(20) NOT NULL,
Plate_Num VARCHAR(6) NOT NULL,
PRIMARY KEY (Car_ID),
FOREIGN KEY (Car_ID) REFERENCES Car(Car_ID)
);

DROP TABLE Compact;
GO

CREATE TABLE Compact(
Car_ID INT NOT NULL,
CarTypeID AS 3 PERSISTED, -- For Compact cars
Make VARCHAR(15) NOT NULL,
Model VARCHAR(20) NOT NULL,
Plate_Num VARCHAR(6) NOT NULL,
PRIMARY KEY (Car_ID),
FOREIGN KEY (Car_ID) REFERENCES Car(Car_ID)
);

DROP TABLE Mid_Size;
GO

CREATE TABLE Mid_Size(
Car_ID INT NOT NULL,
CarTypeID AS 4 PERSISTED, -- For Pickup Trucks
Make VARCHAR(15) NOT NULL,
Model VARCHAR(20) NOT NULL,
Plate_Num VARCHAR(6) NOT NULL,
PRIMARY KEY (Car_ID),
FOREIGN KEY (Car_ID) REFERENCES Car(Car_ID)
);

DROP TABLE Rental;
GO

CREATE TABLE Rental(
Rental_ID INT NOT NULL,
Car_ID INT NOT NULL,
Branch_ID INT NOT NULL,
Start_Date DATE NOT NULL,
End_Date DATE NOT NULL,
PRIMARY KEY (Rental_ID),
FOREIGN KEY (Car_ID) REFERENCES Car(Car_ID),
FOREIGN KEY (Branch_ID) REFERENCES Branch(Branch_ID)
);

DROP TABLE Invoice
GO

CREATE TABLE Invoice(
Invoice_ID INT NOT NULL,
Rental_ID INT NOT NULL,
Customer_ID INT NOT NULL,
Milage INT NOT NULL,
PRIMARY KEY (Invoice_ID),
FOREIGN KEY (Rental_ID) REFERENCES Rental(Rental_ID),
FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID)
);